name: Deploy NGINX (Docker)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build NGINX image
        run: |
          docker build \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            -t nginx-ci:latest \
            ./nginx

      - name: Stop old container
        run: |
          docker rm -f nginx-ci || true

      - name: Run new container
        run: |
          docker run -d \
            --name nginx-ci \
            -p 80:80 \
            nginx-ci:latest

      - name: Health check
        run: |
          sleep 2
          curl -f http://localhost